### ISSUE TITLE
feat: add support for `mini.nvim` plugins

### ISSUE THREAD

**Issue by swahpy** [everviolet/nvim#11]
Hi Thank you for your great colorscheme. I like it very much. I'm a heavy `mini.nvim` user and it is not quite working well together with `mini.nvim` ones. So is it possible to integrate with `mini.nvim`? Thank you very much!

**Comment by comfysage** [comment]
hi, this was already on my list of things to add and I've added support for mini.files recently. my main issue is that I don't use all of the mini plugins so I'm unable to test all of them. I would highly appreciate any support or suggestions as I continue to work on this.

you can expect a draft pr for this sometime this week.

**Comment by swahpy** [comment]
> hi, this was already on my list of things to add and I've added support for mini.files recently. my main issue is that I don't use all of the mini plugins so I'm unable to test all of them. I would highly appreciate any support or suggestions as I continue to work on this.
> 
> you can expect a draft pr for this sometime this week.

`mini.pick` has no highlight on the items which are selected. For others at least for now it is acceptable. I'd love to provide feedbacks.

**Comment by comfysage** [comment]
i made a quick pr for `mini.pick`: https://github.com/comfysage/evergarden/pull/12

**Comment by comfysage** [comment]
fixed with https://github.com/comfysage/evergarden/commit/be3527f111aaceecef08d12682d62ab5263d92c7

**Comment by swahpy** [comment]
hi, sorry but after I applied this change and when I cycled the items in `mini.pick`, it still not showing which one is currently selected. I'm on windows.

**Comment by comfysage** [comment]
this should be fixed with https://github.com/comfysage/evergarden/commit/6523e972e872ef630f52e36bc0e5f8179f5bc7bf

@swahpy im hoping this is working for you now <3

**Comment by swahpy** [comment]
> this should be fixed with [6523e97](https://github.com/comfysage/evergarden/commit/6523e972e872ef630f52e36bc0e5f8179f5bc7bf)
> 
> [@swahpy](https://github.com/swahpy) im hoping this is working for you now <3

Thank you so much for your quick response. I can confirm it works now. Really great!
