### ISSUE TITLE
Setting transparent_background to true does not set the background to transparent.

### ISSUE THREAD

**Issue by erichobson** [everviolet/nvim#18]
Having an issue where I am not able to get the `transparent_background = true` setting to work as expected. I have experimented with other themes that have a similar option and the transparency does work there, so it does not seem to be an issue with my terminal. I have tested it with no other plugins or configurations and the transparency never seems to work. 

Here is my plugin file for your reference: 
```
return {
    "comfysage/evergarden",
    priority = 1000,
    opts = {
        variant = "fall",
        transparent_background = true,
        override_terminal = false,
        style = {
            tabline = { "reverse" },
            search = { "italic" },
            incsearch = { "reverse" },
            types = { "italic" },
            keyword = { "italic" },
            comment = { "italic" },
            sign = { highlight = false },
        },
        integrations = {
            blink_cmp = true,
            lualine = true,
            -- cmp = true,
            -- gitsigns = true,
            -- indent_blankline = true,
            -- nvimtree = true,
            -- rainbow_delimiters = true,
            -- symbols_outline = true,
            -- telescope = true,
            which_key = true,
        },
    },
    config = function(opts)
        vim.cmd.colorscheme("evergarden")
    end,
}
```

As well as my Neovim version: 
```
NVIM v0.11.0-dev-1664+ge71d2c817d
Build type: RelWithDebInfo
LuaJIT 2.1.1736781742
Run ":verbose version" for more info
```

So far the only way I have been able to get the transparency to work with evergarden is if I use a separate plugin to force everything to be transparent, which is not ideal. Thanks!

**Comment by comfysage** [comment]
hi thnx for the issue. i can understand that this was frustrating for you.

can you confirm this was fixed with 01ecfe10 ?

**Comment by erichobson** [comment]
It's all good! I have updated the theme but the transparency is still not working.

**Comment by comfysage** [comment]
it seems like your config is using an outdated format.
the example config was updated here https://github.com/comfysage/evergarden/commit/f7cf3ac68cdae22b036cd7d8fc0baf5c06e78ad4 .

this is an updated version of your personal config <3:
```lua
opts = {
  theme = {
    variant = 'fall',
  },
  editor = {
    transparent_background = true,
    override_terminal = false,
    sign = {
      color = 'surface0',
    },
  },
  style = {
    tabline = { 'reverse' },
    search = { 'italic' },
    incsearch = { 'reverse' },
    types = { 'italic' },
    keyword = { 'italic' },
    comment = { 'italic' },
  },
  integrations = {
    blink_cmp = true,
    -- cmp = true,
    -- gitsigns = true,
    -- indent_blankline = true,
    -- nvimtree = true,
    -- rainbow_delimiters = true,
    -- symbols_outline = true,
    -- telescope = true,
    which_key = true,
  },
}
```

**Comment by erichobson** [comment]
So I gave that a try and tried removing and reinstalling the theme but the transparency is still not working for some reason.

**Comment by comfysage** [comment]
if you set a `config()` field on a plugin you also have to run `setup()` for the plugin manually:
```lua
config = function(_, opts)
	require('evergarden').setup(opts)
	vim.cmd.colorscheme("evergarden")
end,
```

**Comment by erichobson** [comment]
That worked! So is the issues because I used the config field to set the colorscheme within my evergarden plugin file?

**Comment by comfysage** [comment]
by default, if you do *not* set the `config` field, `lazy.nvim` will run `setup()`.
this means that if you set `config` you'll have to manually add `setup()` to your `config()` field.

**Comment by erichobson** [comment]
Awesome, thanks for the help and the great theme!
